### ISSUE TITLE
Add support for resx files

### ISSUE THREAD

**Issue by Fma965** [ever-co/ever-traduora#138]
**Is your feature request related to a problem? Please describe.**
Traduora and a couple other solutions all seem like excellent potential choices for a selfhosted poedit style service however all the decent ones seem to not support resx.

Any chance of adding resx support?

**Describe the solution you'd like**
Add resx support (microsoft visual studio / .net )

example file attached.
[strings.zip](https://github.com/traduora/traduora/files/4842148/strings.zip)

**Comment by rai69** [comment]
Is there anyone working on this feature? I am also interested for this feature for a project that I am working on. 

I also have a clear idea how to implement it, so I was wondering if could add this feature.

**Comment by evereq** [comment]
@rai69 in our team no one working on this. 
Will be great if you can add support for resx files, should be useful for others for sure.

**Comment by evereq** [comment]
@Fma965 we recently merged PR (built by @rai69, thank you!) which introduces support for `resx` files. 
Closing this issue for now.
