### ISSUE TITLE
Docker build / compose fail

### ISSUE THREAD

**Issue by Mistic92** [ever-co/ever-traduora#187]
**Describe the bug**
Docker image is not building. It's failing on multiple steps when I was trying to fix them one after another. 

On step with running build.sh I'm getting permissions denied error.

```
Sending build context to Docker daemon  12.63MB
Step 1/14 : FROM node:12.18-alpine as builder
 ---> e13d60032d4d
Step 2/14 : RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
 ---> Using cache
 ---> 71d58c890bf8
Step 3/14 : RUN npm install --quiet node-gyp -g
 ---> Using cache
 ---> efc1b7150dc6
Step 4/14 : WORKDIR /opt/traduora
 ---> Using cache
 ---> b941f910a4a7
Step 5/14 : COPY bin bin
 ---> 2ffa36e2cb49
Step 6/14 : COPY api api
 ---> 2b974661ff32
Step 7/14 : COPY webapp webapp
 ---> 8aa73c2e2a32
Step 8/14 : RUN bin/build.sh
 ---> Running in d0129bd3353c
/bin/sh: bin/build.sh: Permission denied
The command '/bin/sh -c bin/build.sh' returned a non-zero code: 126
```

**To Reproduce**
On clean repo
1. docker build . 

The same happening for docker-compose build

**Expected behavior**
Build image

** Environment (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 + wsl2
 - Version master branch

**Comment by Mistic92** [comment]
I had to change line end from CRLF to LF in vscode. 
Another issue is that after start Nestjs is finding circular dependency and is stopping. Are tests passing on ci?

**Comment by anthonynsimon** [comment]
@Mistic92  Thanks for reporting this.

I tried building from scratch on Ubuntu (CI), and on Mac OS, and had no issues.

Sounds to me like there are some issues with Windows compatibility. Unfortunately, I don't have a Windows laptop to test this out.

Regarding the CI tests, yes I had a couple of merges in the last few days, and all e2e tests ran successfully.

**Comment by evereq** [comment]
Tested latest docker builds on Windows, works well, closing this ticket.
