### ISSUE TITLE
Add screenshots for the editor in readme or docs?

### ISSUE THREAD

**Issue by CaiMiao** [ever-co/ever-traduora#256]
I have googled your project but can't find screenshots for the editor.

I do some freelance **game translation** and shares them to 1~3 people when I don't have time doing them all by myself, and I'm looking for some self-hosted l10n platform alternate to memsource / memoQ-like.

I like that memsource editor UI is close to memoQ/trados as it have context (multiple lines) being the main element, which is line context oriented, instead of just one line, which ignores contexts between lines and mostly only fits for application l10n (as contexts/notes mostly being a separate field).

I don't except much from opensource projects and most of them are going to localize applications, but I wanted to peek how editor works and see if it have some sort of context previewing that fits for my need, as you don't provide demo sites for us...

I've check mozilla's pontoon, it seems to fit my least need, but it do not have well support for other formats not other self-host guide at the moment afaik.

**Comment by evereq** [comment]
Hi @CaiMiao we start adding screenshots into https://github.com/ever-co/ever-traduora/blob/develop/docs/screenshots.md, please expect more coming today/tomorrow.

**Comment by evereq** [comment]
@CaiMiao we updated that same doc page with even more screenshots, let us know if you have more questions/suggestions, I'll close this ticket for now.
