### ISSUE TITLE
The Getting Started guide doesn't mention anything about MySQL server.

### ISSUE THREAD

**Issue by Lerg** [ever-co/ever-traduora#380]
Since the MySQL server is required to be set up separately from the provided docker image, it should be mentioned on the getting started page.

https://docs.traduora.co/docs/getting-started

Otherwise trying to run the docker image users get an error about failed connection to a database.

Ideally the guide should provide simple instructions on how to get MySQL server running.

**Comment by evereq** [comment]
@Lerg it looks to me that on that page you refer we do suggest to use Docker compose which runs MySQL inside
```
git clone https://github.com/ever-co/ever-traduora
cd ever-traduora
docker-compose -f docker-compose.demo.yaml up
```
(see docker-compose.demo.yaml file)

Also, on the deployment page, we do list MySQL as a requirement https://docs.traduora.co/docs/deployment, etc.

Closing ticket for now.
