### ISSUE TITLE
[Feature] Ability to use PostgreSQL

### ISSUE THREAD

**Issue by vvadymk** [ever-co/ever-traduora#390]
**Is your feature request related to a problem? Please describe.**

Add the ability to use PostgreSQL in addition to MySQL

**Comment by evereq** [comment]
Duplicate to https://github.com/ever-co/ever-traduora/issues/75, but let's keep it open for now till we finish it as PR connected to it :)

**Comment by evereq** [comment]
@vvadymk , I tried your PR (merged it to our repo branch). I was able to register / login and create project, etc, but I am getting error in the terminal output (not in UI), see below

```
postgresdb  | 2023-09-16 19:08:09.388 UTC [82] ERROR:  missing FROM-clause entry for table "projectlocale" at character 8
postgresdb  | 2023-09-16 19:08:09.388 UTC [82] STATEMENT:  SELECT projectLocale.localeCode AS "localeCode", count(*) AS "translated" FROM "project_locale" "projectLocale" LEFT JOIN "translation" "translations" ON "translations"."project_locale_id"="projectLocale"."id" WHERE "projectLocale"."id" IN ($1) AND "translations"."value" <> '' GROUP BY localeCode
traduora    | QueryFailedError: missing FROM-clause entry for table "projectlocale"
```


I am using PostgreSQL v15, maybe it's related? 
You can try using docker-compose I created if you pull branch https://github.com/ever-co/ever-traduora/tree/feat/postgres and run `docker-compose -f .\docker-compose.postgres.yaml  up --build`

**Comment by evereq** [comment]
Hey @vvadymk will you be able to take a look into those issues over the next weeks?

**Comment by vvadymk** [comment]
Hi @evereq. Yes, I will be able to look into those issues this week

**Comment by evereq** [comment]
Hey @vvadymk I assume you did not have time to finalize this one, should I assign our engineer to work on it? (unless you already make it working?)

**Comment by vvadymk** [comment]
Hi @evereq! Sorry, I have a lot of work. I remember what need to be fixed here, I will add this task to my calendar for this weekend. I will do it.

**Comment by vvadymk** [comment]
Hi @evereq . Just let you know, I am working on fix, it is in progress. Will finish it soon

**Comment by bakdakonusuruz** [comment]
> @vvadymk , I tried your PR (merged it to our repo branch and did few tiny improvements). I was able to register / login and create project, etc, but I am getting error in the terminal output (not in UI), see below
> 
> ```
> postgresdb  | 2023-09-16 19:08:09.388 UTC [82] ERROR:  missing FROM-clause entry for table "projectlocale" at character 8
> postgresdb  | 2023-09-16 19:08:09.388 UTC [82] STATEMENT:  SELECT projectLocale.localeCode AS "localeCode", count(*) AS "translated" FROM "project_locale" "projectLocale" LEFT JOIN "translation" "translations" ON "translations"."project_locale_id"="projectLocale"."id" WHERE "projectLocale"."id" IN ($1) AND "translations"."value" <> '' GROUP BY localeCode
> traduora    | QueryFailedError: missing FROM-clause entry for table "projectlocale"
> ```
> 
> I am using PostgreSQL v15, maybe it's related? You can try using docker-compose I created if you pull branch https://github.com/ever-co/ever-traduora/tree/feat/postgres and run `docker-compose -f .\docker-compose.postgres.yaml up --build`

Hi @evereq , I'm still getting the same error, did you guys managed to solve it?

**Comment by evereq** [comment]
@bakdakonusuruz would you mind creating a separate issue and copying that error description to it, we will try to look into it more, but last time I tried to run docker-compose it was all good with PG DB...
