### ISSUE TITLE
MySQL 8 DBPaaS support  ( MySQL 5.7 depecrated )

### ISSUE THREAD

**Issue by hubgitub** [ever-co/ever-traduora#415]
We tried to deploy Traduora on Azure DBaaS and the latest mysql8 version

Support last mySQL or Postgres version

**Comment by evereq** [comment]
@hubgitub what issues you are getting with latest versions?

**Comment by hubgitub** [comment]
@evereq I've checked with my team, With a mysql:8.4 image  in the docker-compose.yaml  these error occurs : 

traduora  | [Nest] 1  - 06/20/2024, 12:36:43 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
traduora  | Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
traduora  |     at Handshake.Sequence._packetToError (/opt/traduora/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)

It's working fine with mysQL 5.7, it's seems to be linked this issue: https://github.com/ever-co/ever-traduora/issues/382

**Comment by evereq** [comment]
@hubgitub ok, so clearly it's about switching to another MySQL package, we will work on it and let you know when it's done. Btw, for PostgreSQL, I think we should use recent versions as we are using more or less the latest PG drivers...

**Comment by evereq** [comment]
Closing as duplicate to https://github.com/ever-co/ever-traduora/issues/382

**Comment by evereq** [comment]
@hubgitub sorry, it looks like we forgot to make a release from our develop branch to master where we already upgraded MySQL to mysql2 and some other improvements. We will do one more update of all packages soon and make a full release :)
