### ISSUE TITLE
Announcing: traduora-cli

### ISSUE THREAD

**Issue by iilei** [ever-co/ever-traduora#42]
I started to implement a [simple cli tool](https://github.com/iilei/traduora-cli), suitable for integrating with npm package scripts.

The aim is to integrate traduora as a build step for fetching remote translations and also pushing locally generated i18n key-value maps to the traduora API.

Integrates best with react-intl messages as [source of truth for the message keys](https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl)

**Comment by CyrilLD** [comment]
Thanks @iilei for this CLI cool !
I tested it for pulling all translation on a given project, and it worked like a charm !

**Comment by iilei** [comment]
@CyrilLD great, thanks for letting me know it's useful for you.

**Comment by anthonynsimon** [comment]
@iilei Hey this is great! Thanks a lot for contributing 💯, let me know if I could help with anything.

**Comment by evereq** [comment]
@iilei thanks! 🚀 . I added it to README here: https://github.com/ever-co/ever-traduora/blob/develop/README.md#features, closing this issue.
