### ISSUE TITLE
Vulnerability notification

### ISSUE THREAD

**Issue by yamerooo123** [ever-co/ever-traduora#431]
**Describe the bug**
Vulnerability notification

**To Reproduce**
Hello, i am a security researcher, i perform a security testing on GitHub open-source projects for free. This is a notification that i have found a critical vulnerability in your product. Information related to vulnerability is provided through **security@ever.co**. Please kindly check the email. Thank you.

**Expected behavior**
Please kindly check the email. Thank you.

**Screenshots**
Please kindly check the email. Thank you.

** Environment (please complete the following information):**

Please kindly check the email. Thank you.

**Additional context**
Please kindly check the email. Thank you.

**Comment by rahul-rocket** [comment]
PR : https://github.com/ever-co/ever-traduora/pull/432

**Comment by yamerooo123** [comment]
Since the vulnerability has been fixed. I will proceed to request CVE ID. CVE will help raise user awareness to upgrade the software to the latest version. Thank you.
